# Generated by Django 4.2.7 on 2024-11-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ntn_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
