# Generated by Django 4.2.7 on 2024-11-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_invoice_is_taxed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='is_taxed',
            field=models.BooleanField(default=False),
        ),
    ]
