# Generated by Django 4.2.7 on 2024-12-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_alter_invoice_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceowner',
            name='phone_2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
