# Generated by Django 4.2.7 on 2025-02-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_alter_invoice_grand_total_alter_invoice_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceowner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_owner/logos/'),
        ),
        migrations.AddField(
            model_name='invoiceowner',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_owner/signatures/'),
        ),
    ]
