# Generated by Django 4.2.7 on 2025-02-09 21:19

from django.db import migrations
import imagekit.models.fields
import invoice_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0005_alter_invoiceowner_logo_alter_invoiceowner_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceowner',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=invoice_app.utils.upload_logo),
        ),
        migrations.AlterField(
            model_name='invoiceowner',
            name='signature',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=invoice_app.utils.upload_sign),
        ),
    ]
