# Generated by Django 4.2.7 on 2025-02-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0007_alter_invoiceowner_logo_alter_invoiceowner_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceowner',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceowner',
            name='account_title',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceowner',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceowner',
            name='bank',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceowner',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceowner',
            name='ntn_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
