# Generated by Django 4.2.7 on 2025-02-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0008_invoiceowner_is_onboarded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceowner',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoiceowner',
            name='ntn_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
