# Generated by Django 4.2.7 on 2025-03-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0011_remove_invoice_client_client_invoice_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_owner',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice_app.client'),
            preserve_default=False,
        ),
    ]
